import re

ABBREVIATIONS = {
    'ubnd': 'ủy ban nhân dân',
    'bvmt': 'bảo vệ môi trường',
    'tcct': 'tổng cục chính trị',
    'catp': 'công an thành phố',
    'nơxh': 'nhà ở xã hội',
    'bđkh': 'biến đổi khí hậu',
    'hđnd': 'hội đồng nhân dân',
    'csđt': 'cảnh sát điều tra',
    'tnhh': 'trách nhiệm hữu hạn',
    'nđcp': 'nghị định chính phủ',
    'ttđt': 'thông tin điện tử',
    'lhpn': 'liên hiệp phụ nữ',
    'đbqh': 'đại biểu quốc hội',
    'qđxphc': 'quy định xử phạt hành chính',
    'ktgs': 'kiểm tra giám sát',
    'hđqt': 'hội đồng quản trị',
    'pctt': 'phòng chống thiên tai',
    'qđttg': 'quyết định thủ tướng',
    'ttbnv': 'thông tư bộ nội vụ',
    'tkcn': 'tìm kiếm cứu nạn',
    'nttt': 'nền tảng tư tưởng',
    'ptds': 'phòng thủ dân sự',
    'qsdđ': 'quyền sử dụng đất',
    'bct': 'bộ chính trị',
    'vbpl': 'văn bản pháp luật',
    'tttt': 'thông tin truyền thông',
    'tt tt': 'thông tin và truyền thông',
    'cntt': 'công nghệ thông tin',
    'tnmt': 'tài nguyên môi trường',
    'tn mt': 'tài nguyên và môi trường',
    'ktth': 'kinh tế tuần hoàn',
    'tphn': 'thành phố hà nội',
    'tphcm': 'thành phố hồ chí minh',
    'thhp': 'thành phố hải phòng',
    'tpct': 'thành phố cần thơ',
    'tpđn': 'thành phố đà nẵng',
    'nsnn': 'ngân sách nhà nước',
    'ttxvn': 'thông tấn xã việt nam',
    'xhcn': 'xã hội chủ nghĩa',
    'dtts': 'dân tộc thiểu số',
    'mtqg': 'mục tiêu quốc gia',
    'đbsh': 'đồng bằng sông hồng',
    'vđtc': 'vốn đầu tư công',
    'xdcb': 'xây dựng cơ bản',
    'gpmb': 'giải phóng mặt bằng',
    'đbscl': 'đồng bằng sông cửu long',
    'cttđt': 'cổng thông tin điện tử',
    'gdđt': 'giáo dục đào tạo',
    'gd&đt': 'giáo dục và đào tạo',
    'gd đt': 'giáo dục và đào tạo',
    'vhttdl': 'văn hóa thể thao và du lịch',
    'qpan': 'quốc phòng an ninh',
    'mttq': 'mặt trận tổ quốc',
    'qltt': 'quản lý thị trường',
    'bđbp': 'bộ đội biên phòng',
    'bch': 'ban chấp hành',
    'ktxh': 'kinh tế xã hội',
    'hvpn': 'học viện phụ nữ',
    'đhct': 'đại học cần thơ',
    'đnb': 'đông nam bộ',
    'byt': 'bộ y tế',
    'đtn': 'đoàn thanh niên',
    'tncs': 'thanh niên cộng sản',
    'lhtn': 'liên hiệp thanh niên',
    'csgt': 'cảnh sát giao thông',
    'cstt': 'cảnh sát trật tự',
    'cscđ': 'cảnh sát cơ động',
    'lđtb': 'lao động thương binh',
    'qđnd': 'quân đội nhân dân',
    'ckqt': 'cửa khẩu quốc tế',
    'tcđt': 'tác chiến điện tử',
    'uvtv': 'ủy viên thường vụ',
    'tthc': 'thủ tục hành chính',
    'ktkt': 'kinh tế kỹ thuật',
    'qppl': 'quy phạm pháp luật',
    'tctk': 'tổng cục thống kê',
    'pccc': 'phòng cháy chữa cháy',
    'cnch': 'cứu nạn cứu hộ',
    'bhyt': 'bảo hiểm y tế',
    'bhxh': 'bảo hiểm xã hội',
    'dnnn': 'doanh nghiệp nhà nước',
    'qcvn': 'quy chuẩn kỹ thuật quốc gia',
    'bvtv': 'bảo vệ thực vật',
    'tnlđ': 'tai nạn lao động',
    'bcsđ': 'ban cán sự đảng',
    'llvt': 'lực lượng vũ trang',
    'anct': 'an ninh chính trị',
    'antt': 'an ninh trật tự',
    'chqs': 'chỉ huy quân sự',
    'ttatxh': 'trật tự an toàn xã hội',
    'mttw': 'mặt trận trung ương',
    'cbcnv': 'cán bộ công nhân viên',
    'htx': 'hợp tác xã',
    'nxb': 'nhà xuất bản',
    'btc': 'bộ tài chính',
    'kcb': 'khám chữa bệnh',
    'ntm': 'nông thôn mới',
    'bđs': 'bất động sản',
    'lhq': 'liên hợp quốc',
    'oda': 'hỗ trợ phát triển chính thức',
    'ttg': 'thủ tướng',
    'bcs': 'ban cán sự',
    'bca': 'bộ công an',
    'ccb': 'cựu chiến binh',
    'pttđ': 'phong trào thi đua',
    'gcnqsdđ': 'giấy chứng nhận quyền sử dụng đất',
    'gtclqg': 'giải thưởng chất lượng quốc gia',
    'ttnhnn': 'thông tư ngân hàng nhà nước',
    'nhnn': 'ngân hàng nhà nước',
    'nnptnt': 'nông nghiệp và phát triển nông thôn',
    'ptnt': 'phát triển nông thôn',
    'đvtn': 'đoàn viên thanh niên',
    'thpt': 'trung học phổ thông',
    'thcs': 'trung học cơ sở',
    'ctcp': 'công ty cổ phần',
    'ubmttqvn': 'ủy ban mặt trận tổ quốc việt nam',
    'tw': 'trung ương',
    'tt': 'thông tư',
    'ct': 'chỉ thị',
    'qđ': 'quyết định',
    'nq': 'nghị quyết',
    'tp': 'thành phố',
    'hn': 'hà nội',
    'hcm': 'hồ chí minh',
    'cđs': 'chuyển đổi số',
    'btv': 'ban thường vụ',
    'đbp': 'điện biên phủ',
    'bvh': 'bộ văn hóa',
    'bnn': 'bệnh nghề nghiệp',
    'bxd': 'bộ xây dựng',
    'bnv': 'bộ nội vụ',
    'hp': 'hải phòng',
    'đn': 'đà nẵng',
    'nđ': 'nghị định',
    'đh': 'đại học',
    'cp': 'chính phủ',
    'cđ': 'chỉ đạo',
    'vn': 'việt nam',
    'qđ': 'quyết định',
    'xh': 'xã hội',
    'nn': 'nông nghiệp',
    'cn': 'công nghiệp',
    'pv': 'phóng viên',
    'hlv': 'huấn luyện viên'
}

def convert_abbreviations(text: str) -> str:
    text = ' ' + text + ' '

    for abbreviation, full_form in ABBREVIATIONS.items():
        pattern = r"(?<=\s)" + re.escape(abbreviation) + r"(?=\s)"
        text = re.sub(pattern, full_form, text)

    text = re.sub(r'\s+', ' ', text)

    return text.strip()